name: pilottone
channels:
  - ismrmrd
  - conda-forge
  - defaults
dependencies:
  - python
  - ismrmrd::ismrmrd-python=1.14.1
  - ismrmrd::siemens_to_ismrmrd=1.2.11
  - boost=1.76.0         # For ismrmrd
  - libxml2=2.9.12       # For ismrmrd
  - h5py=3.7.0           # For ismrmrd
  - matplotlib=3.8.4     # used by rgb.py and provides various visualization tools including colormaps
  - numpy=1.26.0
  - git=2.30.2
  - ipykernel
  - pandas
  - pyfftw
  - hyperspy
  - pip
  - pip:
    - rtoml==0.10.0
