# File Path config
data_folder     = ""
DATA_ROOT       = "/"

# Reconstruction control
[reconstruction]
recon_type      = "viewsharing" # 'viewsharing', 'ttv', 'xdgrasp'
server_port     = 9028  # Port that server is currently running on.
show_images     = true  # Whether or not to show images after reconstruction.
output_folder   = "output_recons"

# EDITER control
[editer]
prewhiten           = true
autosniffer_select  = false
sensing_coils       = [1, 15, 16, 17] # Coils to use for sensing.
gpu_device          = 1     # GPU device to use for EDITER, -1 for CPU.
interference_freq   = 24e6  # Frequency of the interference signal, to be used in autosniffer_select.

[pilottone]
pt_freq = 24e6
prewhiten = true
discard_badcoils = true # Uses the same algorithm as autosniffer_select to discard bad coils.
sensing_coils       = [15, 16, 17] # Coils to use for sensing.
show_outputs    = false # Whether or not to show the outputs of the pilottone extraction.
golay_filter_len = 81 # Golay filter length for initial denoising.

[pilottone.respiratory]
freq_start          = 0.05 # [Hz] Lower frequency limit for respiratory bandpass filter
freq_stop           = 0.9 # [Hz] Upper frequency limit for respiratory bandpass filter
corr_threshold      = 0.9 # Correlation threshold for respiratory coil selection
initial_channel      = -1 # Initial guess for the respiratory coil selection
separation_method = "sobi" # SOBI or PCA

[pilottone.cardiac]
freq_start          = 1 # [Hz] Lower frequency limit for cardiac bandpass filter
freq_stop           = 20 # [Hz] Upper frequency limit for cardiac bandpass filter
corr_threshold      = 0.9 # Correlation threshold for cardiac coil selection
initial_channel     = 'Body_6:1:B13' # Initial guess for the cardiac coil selection
separation_method = "pca" # SOBI or PCA

[saving]
remove_os               = false # Remove 2x oversampling when saving the raw data
save_model_subtracted   = false # Whether or not to save PT model subtracted data in main_pilottone_extract script.
save_pt_waveforms       = false # Whether or not to save pilottone waveforms in main_pilottone_extract script.
save_pt_separate        = true # Whether or not to save pilottone waveforms in separate npz files.