# File Path config
output_filename = "vol0622_pilottone"

data_folder     = "vol0622_20230522"
raw_file        = "67"
DATA_ROOT       = '/mnt/LIN_DATA/MRI_DATA'

# Reconstruction control
recon_type      = "viewsharing" # 'viewsharing', 'ttv', 'xdgrasp'

