# File Path config
output_filename = "vol0622_pilottone"

data_folder     = "vol0622_20230522"
raw_file        = "67"
DATA_ROOT       = '/mnt/LIN_DATA/MRI_DATA'

# Reconstruction control
[reconstruction]
recon_type      = "viewsharing" # 'viewsharing', 'ttv', 'xdgrasp'
server_port     = 9028  # Port that server is currently running on.
show_images     = true  # Whether or not to show images after reconstruction.
output_folder   = "output_recons"

# EDITER control
[editer]
prewhiten           = true
autosniffer_select  = false
sensing_coils       = [1, 15, 16, 17] # Coils to use for sensing.
gpu_device          = 1     # GPU device to use for EDITER, -1 for CPU.
interference_freq   = 24e6  # Frequency of the interference signal, to be used in autosniffer_select.

[pilottone]
pt_freq = 24e6
prewhiten = true
discard_badcoils = true # Uses the same algorithm as autosniffer_select to discard bad coils.
sensing_coils       = [15, 16, 17] # Coils to use for sensing.

[saving]
remove_os               = false # Remove 2x oversampling when saving the raw data
save_model_subtracted   = false # Whether or not to save PT model subtracted data in main_pilottone_extract script.
save_pt_waveforms       = false # Whether or not to save pilottone waveforms in main_pilottone_extract script.
save_pt_separate        = true # Whether or not to save pilottone waveforms in separate npz files.