[project]
name = "pylottone"
version = "0.1.4"
description = "PylotToneMRI is a Python Toolbox with an emphasis on high-amplitude pilot tone applied to spiral MR imaging."
readme = "README.md"
authors = [
    { name = "Bilal Tasdelen", email = "tasdelen@usc.edu" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pyfftw>=0.15.0",
    "scipy",
]

[project.optional-dependencies]
mrd = ["ismrmrd>=1.14.1"]
gpu = ["cupy-cuda12x>=13.6.0"]
ui = [
    "ipywidgets>=8",
    "pyside6>=6.9.1",
]
segmentation = ["mpl-image-segmenter>=0.2.1"]

[project.scripts]
send_to_recon_server = "pylottone.reconstruction.send_to_recon_server:main_cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ipympl>=0.9.7",
    "jupyterlab>=4.4.6",
    "mpl-interactions>=0.24.2",
    "pandas>=2.3.2",
    "pyarrview",
]

[tool.uv.sources]
pyarrview = { git = "https://github.com/btasdelen/pyArrView" }
