PILOTTONE_WAVEFORM_ID = 1025
PILOTTONE_CH = {'RESP': 0, 'CARDIAC': 1, 'CARDIAC_TRIGGERS': 2, 'CARDIAC_DERIVATIVE': 3, 'DERIVATIVE_TRIGGERS': 4}
ECG_WAVEFORM_ID = 0
PULSEOX_WAVEFORM_ID = 1
RESP_WAVEFORM_ID = 2
EXT1_WAVEFORM_ID = 3
EXT2_WAVEFORM_ID = 4
RESPPT_WAVEFORM_ID = 12